"""
Django settings for OM_platform project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import datetime
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fnw4k)9%3s-(1#tj1d=v0&@d=@9cjjx4v!1uv(oggaki!593hc'

# SECURITY WARNING: don't run with debug turned on in production!
# python manage.py runserver 0.0.0.0:8000 --insecure
DEBUG = False

ALLOWED_HOSTS = ['*']

SSO_DOMAIN = "10.126.59.18:8080"
# SSO_DOMAIN = "popeye.ds.gome.com.cn"
CMDB_HOST = "10.58.60.251:8888"
# CMDB_HOST = "gom.ds.gome.com.cn"
APP_KEY = "7b37ca05cb0a4e759fdfc28bdb6ab31b"
# APP_KEY = "4329927328774d2d921a8fa32d7171d1"

SSO_TOKEN = "gome_sso_token"



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Daily_app',
    'ansible_app',
    'Budget_app',
    'IDC_app',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OM_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OM_platform.wsgi.application'

SESSION_COOKIE_AGE = 1800

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'OM_db',
        'HOST': '10.58.60.177',
        'USER': 'root',
        'PASSWORD': 'pwd@1234',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'OM',
#         'HOST': '10.58.60.177',
#         'USER': 'root',
#         'PASSWORD': 'pwd@1234',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'
# TIME_ZONE = 'UTC'


USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
LOGIN_URL = '/account/login/'

STATIC_URL = '/static/'
STATICFILES_DIRS = (
     os.path.join(BASE_DIR, 'static'),
 )


def now_time():
    new_time = str(datetime.datetime.now() + datetime.timedelta()).split(".")[0]
    # new_time = str(datetime.datetime.now()).split(".")[0]
    return new_time

PING_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/ping_file/"
PASSWORD_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/pwd_file/"
PASSWORD_SERVER = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/pwd_server/"
IP_FILE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/ip_file/"
SCRIPT_FILE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/scripts_file/"
BUDGET_FILE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/budget_file/"
IPTABLES_SCRIPTS = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/iptables_scripts/"
IDC_FILES = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/upload_file/idc_file/"
ANSIBLE_FILE_DIR = '/ansible_tmp/'